# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0004_auto_20151223_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fts.List'),
        ),
    ]
